<!DOCTYPE html>

<html lang="fr">

    <head>
        <meta charset="utf-8">
        <title>Layout</title>
        <link rel="stylesheet" href="style.css" />
    </head>
    
    <body>
        <?php
        require("templates/partials/_header.phtml");
        
        require("templates/".$template."/".$template.".phtml"); 
        
        require("templates/partials/_footer.phtml");
        ?>
    </body>

</html>